SCSuiteConfiguration.localization_strings = {    scsuitemenu = "SCSuite Options",
    scsuitemenudesc = "Main SCSuite Options Menu",
    mute_bain_name = "Mute Bain",
    mute_bain_title = "Toggle Mute Bain",
    mute_bain_desc = "When enabled all Bain voice overs are disabled - except on required maps",
    mute_bain_enabled = "mute_bain_enabled",
    mute_bain_rats = "Use: {1} now",
    cheat_submenu_name = "Cheats/Hacks",
    cheat_submenu_title = "Cheats/Hacks",
    cheat_submenu_desc = "A menu of cheats",  
    instant_drill_name = "Instant Drill",
    instant_drill_title = "Toggle Instant Drilling",
    instant_drill_desc = "When enabled any subsequently placed drills will finish instantly",
    instant_drill_enabled = "instant_drill_enabled",    
    mission_menu_title = "Toggle Mission Menu",
    mission_menu_desc = "When enabled pressing F2 will open a menu to load any mission",
    mission_menu_enabled = "mission_menu_enabled",
    toggle_mask_name = "ToggleMask",
    toggle_mask_title = "Toggle Mask",
    toggle_mask_desc = "When enabled equipping mask becomes a toggle. Press key again to stop.",
    toggle_mask_enabled = "toggle_mask_enabled",   
}